### ISSUE TITLE
Adding Dark Mode to The Website

### ISSUE THREAD

**Issue by VaibhavSharma24** [sruti2024/PRO_Act#181] opened 2021-05-02 14:28 UTC
### **Feature request**:
I would love to add a dark mode to this website which will enhance the website.

**Comment by SaiSudhaV** [comment] 2021-05-02 16:47
Hello @VaibhavSharma24 
The issue is already there #10
If you think its different from that issue let me know we'll reopen it again
Thank you for your interest!!

**Comment by Aryamanz29** [comment] 2021-05-04 18:30
> Hello @VaibhavSharma24
> There is a similar issue #10 which is already done
> If you think its different from that issue let me know we'll reopen it again
> Thank you for your interest!!

Hii 👋 @SaiSudhaV 
This #10 PR is reverted (see [this](https://github.com/sruti2024/PRO_Act/pull/174)) since it breaks the existing project code and this feature still not implemented in the project. I think we should assign this issue to @VaibhavSharma24 😅. What do you think?

**Comment by SaiSudhaV** [comment] 2021-05-12 16:57
@VaibhavSharma24 Any update?

**Comment by arpit456jain** [comment] 2021-05-17 10:02
@SaiSudhaV please assign me

**Comment by arpit456jain** [comment] 2021-05-17 11:25
@SaiSudhaV please ask @sruti2024 to merge that PR for ui enhancement of view projects before any merge conflicts occurs 🙏🙏

**Comment by arpit456jain** [comment] 2021-05-20 14:37
@sruti2024 @SaiSudhaV kindly review my PR for dark mode

**Closed** 2021-05-22 13:52 UTC
Labels: Level3, enhancement, gssoc21
